/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileIndexRouteImport } from './routes/mobile.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as MobileTrackingRouteImport } from './routes/mobile.tracking'
import { Route as MobileScannerRouteImport } from './routes/mobile.scanner'
import { Route as MobileProductsRouteImport } from './routes/mobile.products'
import { Route as MobileMarketplaceRouteImport } from './routes/mobile.marketplace'
import { Route as DashboardTrackingRouteImport } from './routes/dashboard.tracking'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MobileTrackingRoute = MobileTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => MobileRoute,
} as any)
const MobileScannerRoute = MobileScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => MobileRoute,
} as any)
const MobileProductsRoute = MobileProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MobileRoute,
} as any)
const MobileMarketplaceRoute = MobileMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => MobileRoute,
} as any)
const DashboardTrackingRoute = DashboardTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/mobile/marketplace': typeof MobileMarketplaceRoute
  '/mobile/products': typeof MobileProductsRoute
  '/mobile/scanner': typeof MobileScannerRoute
  '/mobile/tracking': typeof MobileTrackingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mobile/': typeof MobileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/mobile/marketplace': typeof MobileMarketplaceRoute
  '/mobile/products': typeof MobileProductsRoute
  '/mobile/scanner': typeof MobileScannerRoute
  '/mobile/tracking': typeof MobileTrackingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/mobile': typeof MobileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/mobile/marketplace': typeof MobileMarketplaceRoute
  '/mobile/products': typeof MobileProductsRoute
  '/mobile/scanner': typeof MobileScannerRoute
  '/mobile/tracking': typeof MobileTrackingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mobile/': typeof MobileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mobile'
    | '/signup'
    | '/dashboard/insights'
    | '/dashboard/marketplace'
    | '/dashboard/products'
    | '/dashboard/tracking'
    | '/mobile/marketplace'
    | '/mobile/products'
    | '/mobile/scanner'
    | '/mobile/tracking'
    | '/dashboard/'
    | '/mobile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/insights'
    | '/dashboard/marketplace'
    | '/dashboard/products'
    | '/dashboard/tracking'
    | '/mobile/marketplace'
    | '/mobile/products'
    | '/mobile/scanner'
    | '/mobile/tracking'
    | '/dashboard'
    | '/mobile'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/mobile'
    | '/signup'
    | '/dashboard/insights'
    | '/dashboard/marketplace'
    | '/dashboard/products'
    | '/dashboard/tracking'
    | '/mobile/marketplace'
    | '/mobile/products'
    | '/mobile/scanner'
    | '/mobile/tracking'
    | '/dashboard/'
    | '/mobile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MobileRoute: typeof MobileRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/mobile/tracking': {
      id: '/mobile/tracking'
      path: '/tracking'
      fullPath: '/mobile/tracking'
      preLoaderRoute: typeof MobileTrackingRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/scanner': {
      id: '/mobile/scanner'
      path: '/scanner'
      fullPath: '/mobile/scanner'
      preLoaderRoute: typeof MobileScannerRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/products': {
      id: '/mobile/products'
      path: '/products'
      fullPath: '/mobile/products'
      preLoaderRoute: typeof MobileProductsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/marketplace': {
      id: '/mobile/marketplace'
      path: '/marketplace'
      fullPath: '/mobile/marketplace'
      preLoaderRoute: typeof MobileMarketplaceRouteImport
      parentRoute: typeof MobileRoute
    }
    '/dashboard/tracking': {
      id: '/dashboard/tracking'
      path: '/tracking'
      fullPath: '/dashboard/tracking'
      preLoaderRoute: typeof DashboardTrackingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardTrackingRoute: typeof DashboardTrackingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardTrackingRoute: DashboardTrackingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MobileRouteChildren {
  MobileMarketplaceRoute: typeof MobileMarketplaceRoute
  MobileProductsRoute: typeof MobileProductsRoute
  MobileScannerRoute: typeof MobileScannerRoute
  MobileTrackingRoute: typeof MobileTrackingRoute
  MobileIndexRoute: typeof MobileIndexRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileMarketplaceRoute: MobileMarketplaceRoute,
  MobileProductsRoute: MobileProductsRoute,
  MobileScannerRoute: MobileScannerRoute,
  MobileTrackingRoute: MobileTrackingRoute,
  MobileIndexRoute: MobileIndexRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MobileRoute: MobileRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
